apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: kubevirt-cluster-cred
  namespace: aap
spec:
  connection_secret: aap-access
  name: kubevirt-cluster-cred
  credential_type: custom
  # This credential is a helper example that contains the remote cluster API endpoint and token.
  # The Automation Controller (AAP) expects custom credential types to be created in the
  # UI with an environment-variable injection mapping so the KubeVirt inventory plugin can
  # read K8S_AUTH_HOST and K8S_AUTH_API_KEY. Operator behavior may vary; if your operator
  # supports injecting env vars from credential inputs, configure the mapping accordingly.
  inputs:
    api_url: "https://api.openshift.example.com:6443"
    token: "<REPLACE_WITH_REMOTE_CLUSTER_TOKEN>"

# After creating this credential, configure AAP to inject the values into environment
# variables (K8S_AUTH_HOST -> api_url, K8S_AUTH_API_KEY -> token) when running the
# inventory sync. If your operator requires a Kubernetes secret instead, use
# 00-aap-oc-token-secret.yaml and link to it via the UI or operator-specific settings.
