apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  # Platform
  image_pull_policy: IfNotPresent
  # Components
  controller:
    disabled: false
    name: aap-controller
  hub:
    disabled: false
    name: aap-hub
    ## uncomment if using file storage for Content pod
    # storage_type: file
    # file_storage_storage_class: your-rwx-storage-class
    # file_storage_size: 10Gi
    ## uncomment if using S3 storage for Content pod
    storage_type: S3
    object_storage_s3_secret: aap-hub-s3
    ## uncomment if using Azure storage for Content pod
    # storage_type: azure
    # object_storage_azure_secret: azure-secret-name
  eda:
    disabled: false
  lightspeed:
    disabled: true
