apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: summit-connect-build-cache
  namespace: summit-connect
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "lvms-vg1"  # Use default LVMS storage class