## Template: create a pull/push secret for quay.io. Replace <BASE64_ENCODED_DOCKERCONFIGJSON> with the contents of
## `echo -n '{"auths":{"quay.io":{"username":"<USERNAME>","password":"<TOKEN>","auth":"<BASE64>"}}}' | base64`.
apiVersion: v1
kind: Secret
metadata:
  name: quay-push-secret
  namespace: summit-connect
  annotations:
    build.shipwright.io/referenced.secret: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "<BASE64_ENCODED_DOCKERCONFIGJSON>"
