{{- if .Values.vm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (printf "%s-headless" (include "summit-connect.fullname" .)) }}
  namespace: {{ .Values.vm.namespace | default .Release.Namespace }}
  labels:
    {{- include "summit-connect.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "summit-connect.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
{{- end }}