{{- if and .Values.vm.enabled .Values.secrets.createKubeconfigsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kubeconfigsSecretName }}
  namespace: {{ .Values.vm.namespace | default .Release.Namespace }}
  labels:
    {{- include "summit-connect.labels" . | nindent 4 }}
type: Opaque
data:
  # Add your kubeconfig files here
  # Example:
  # kubeconfig: {{ "apiVersion: v1\nkind: Config..." | b64enc | quote }}
  # 
  # NOTE: It's recommended to create this secret externally using:
  # oc create secret generic summit-connect-kubeconfigs --from-file .kubeconfigs
{{- end }}