{{- if and .Values.vm.enabled .Values.sshAccess.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sshAccess.secretName }}
  namespace: {{ .Values.vm.namespace | default .Release.Namespace }}
  labels:
    {{- include "summit-connect.labels" . | nindent 4 }}
type: Opaque
data:
  # SSH public key - base64 encoded
  # Replace this with your actual SSH public key
  key: {{ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC..." | b64enc | quote }}
  # 
  # NOTE: It's recommended to create this secret externally using:
  # oc create secret generic ssh-key --from-file=key=~/.ssh/id_rsa.pub
{{- end }}